language: javascript
perl:
  - "5.24"

before_install:
  - npm install tiddlywiki

install: true

script:
  - cp -r plugins/* node_modules/tiddlywiki/plugins/
  - perl -i -pe 'BEGIN { use POSIX qw(strftime) } s/\$\{strftime\s+(.*?)\}\$/strftime "$1",gmtime()(stat $ARGV)[9])/g node_modules/tiddlywiki/plugins/*/*/*.js'
  - ./node_modules/.bin/tiddlywiki . --output output --build gui
  - ./node_modules/.bin/tiddlywiki . --output output/library --build library

deploy:
  provider: pages
  local-dir: output
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
